### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-5ni0w#3]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by ashishlotake** [comment]
Fix for bug #3


![Screenshot_20220802_121748](https://user-images.githubusercontent.com/62111173/182312212-b2e97fed-
b81f-48b0-8fce-ee2a9d852050.png)

**Comment by ashishlotake** [comment]
Fix for bug #3
## Screenshot

![Screenshot_20220802_121748](https://user-images.githubusercontent.com/62111173/182312654-5f12ff85-1e9b-4c11-9a57-e63bbd9573cb.png)
